# Website name
title: Saikiran Juttu | Robotics Portfolio

# ✅ Use your actual GitHub Pages URL
baseURL: "https://juttu-s.github.io/saikiran_juttu.github.io/"

# ✅ Important for GitHub Pages
canonifyURLs: true
relativeURLs: true

############################
## LANGUAGE
############################
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################
build:
  writeStats: true

enableGitInfo: false
summaryLength: 30

pagination:
  pagerSize: 10

enableEmoji: true
enableRobotsTXT: true

footnotereturnlinkcontents: <sup>^</sup>

ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]

permalinks:
  authors: "/author/:slug/"
  project: "/project/:slug/"
  posts: "/posts/:slug/"

disableAliases: false

outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart

timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

markup:
  _merge: deep
  highlight:
    lineNos: false

security:
  _merge: deep

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
