# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Northeastern University'
    description: 'Robotics Software Engineer with an MS in Robotics from Northeastern University, specializing in SLAM, state estimation, multi-robot planning, and ROS 2 autonomy on embedded platforms.'
    twitter: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Saikiran Juttu"

# Site footer
footer:
  copyright:
    notice: '© {year} Saikiran Juttu. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  # sharing:
  #   enable: false